module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    MUTI_SELECT_ROOMS: "MUTI_SELECT_ROOMS",
    MUTI_SELECT_ROOMS_FLOR: "MUTI_SELECT_ROOMS_FLOR",
    MUTI_SELECT_ROOMS_TYPE: "MUTI_SELECT_ROOMS_TYPE",
    MUTI_SELECT_ROOMS_PRICE: "MUTI_SELECT_ROOMS_PRICE",
    MUTI_SELECT_ROOMS_IMG: "MUTI_SELECT_ROOMS_IMG",
    MOVE_ROOM: "MOVE_ROOM",
    SIGNATURE: "SIGNATURE",
    SHOW_IMG_ROOM: "SHOW_IMG_ROOM",
    CONFIRMATION_RESET_PASSWORD: "CONFIRMATION_RESET_PASSWORD",
    CONFIRMATION_DELETE_USER: "CONFIRMATION_DELETE_USER",
    CONFIRMATION_DELETE: "CONFIRMATION_DELETE",
    CONFIRMATION_DELETE_CUSTOM: "CONFIRMATION_DELETE_CUSTOM",
    CONFIRMATION_DELETE_CODE: "CONFIRMATION_DELETE_CODE",

    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    CREATE_HOME: "CREATE_HOME",
    CREATE_POLICY: "CREATE_POLICY",
    CREATE_FURNITURE: "CREATE_FURNITURE",
    UPDATE_ROOM: "UPDATE_ROOM",
    CREATE_ROOM:"CREATE_ROOM",
    LIST_HOME: "LIST_HOME",
    DETAILS_ROOM: "DETAILS_ROOM",
    DEPOSIT_ROOM: "DEPOSIT_ROOM",
    ADD_CUSTOMER: "ADD_CUSTOMER",
    CONTRACT_ROOM: "CONTRACT_ROOM",
    EXPORT_CONTRACT_ROOM: "EXPORT_CONTRACT_ROOM",
  },

  TYPES_DELETE: {
    LEAD_DELETE: "LEAD_DELETE",
    RESET_PASSWORD_USER: "RESET_PASSWORD_USER",
    DELETE_USER: "DELETE_USER",
    DELETE: "DELETE_HOME",
    DELETE_ROOM: "DELETE_ROOM",
    DELETE_DEPOSIT: "DELETE_DEPOSIT",
    DELETE_CONTRACT: "DELETE_CONTRACT"

  },
});
